Talend/talend-cloud-installer

- .reviewboardrc
- Puppetfile
- Puppetfile.lock
- hieradata/common.yaml
- site/profile/manifests/base.pp
- site/profile/manifests/common/cloudwatch.pp
Reviewed here : https://review.tipaas.com/r/1004/
> DEVOPS-1289 : integration of the Cloudwatch Agent

- hieradata/puppet_role/tic_services_external.yaml
- hieradata/puppet_role/tic_services_internal.yaml
> move healthcheck-service-core to the end of infra karaf boot feature

- hieradata/puppet_role/frontend.yaml
- hieradata/puppet_role/tic_services_external.yaml
- hieradata/puppet_role/tic_services_internal.yaml
- spec/acceptance/frontend_spec.rb
- spec/acceptance/tic_services_external_spec.rb
- spec/acceptance/tic_services_internal_spec.rb
Enable /nginx_status on frontend and services
> Devops 2699

- Puppetfile.lock
- hieradata/puppet_role/ecs.yaml
- hieradata/puppet_role/frontend.yaml
- hieradata/puppet_role/mongodb.yaml
- packer/azure-template.json
- site/profile/manifests/docker/ecs_agent.pp
- spec/acceptance/shared/mongodb.rb
This template is required in order to prepare Azure virtual hard disks, and further convert them to Images.
Testing made
https://ci-cloud.datapwn.com/job/test-base-image-azure2/42/console
> DEVOPS-2774 Commit Azure packer template to github

- hieradata/puppet_role/frontend.yaml
Added production change https://jira.talendforge.org/browse/DEVOPS-2476
> aligning with production changes

- hieradata/puppet_role/mongodb.yaml
- site/profile/files/etc/init.d/disable-transparent-hugepages
- site/profile/files/etc/security/limits.d/mongod.conf
- site/profile/files/etc/sysctl.d/mongod.conf
- site/profile/manifests/mongodb.pp
- spec/acceptance/shared/mongodb.rb
https://docs.mongodb.com/manual/administration/production-checklist-operations/
https://docs.mongodb.com/manual/administration/production-notes/
https://docs.mongodb.com/manual/reference/ulimit/#recommended-ulimit-settings
> DEVOPS-3193: tune system for Mongo, reduce logs for prod

- scripts/local_dev_tests.sh
When you only modified a bunch of Puppet code, do not create again everything.
> add redo mode

- hieradata/puppet_role/kafka.yaml
tested in talend-cloud-integration
> TDS-2864: rename tds kafka local-offsets topic and fix it to only one partition

- Puppetfile
- Puppetfile.lock
- metadata.json
- spec/acceptance/shared/mongodb.rb
Do not merge yet.
WORK IN PROGRESS with @jmlrt
> change mongodb puppet module source

- Puppetfile.lock
- spec/acceptance/frontend_spec.rb
> DEVOPS-3926: Remove ROOT webapp in TIC frontend tomcat config

- hieradata/common.yaml
Remove the screen package from all roles
> DEVOPS-3985: Remove screen package

- Puppetfile.lock
- hieradata/puppet_role/tic_services_external.yaml
- hieradata/puppet_role/tic_services_internal.yaml
- spec/acceptance/tic_services_external_spec.rb
- spec/acceptance/tic_services_internal_spec.rb
Tested by local test execution
> DEVOPS-3979: Add licenses URL to CMS config; fix tests

- hieradata/puppet_role/ecs.yaml
- site/profile/manifests/docker/ecs_agent.pp
> update ecs agent version

- hieradata/puppet_role/mongodb.yaml
- spec/acceptance/shared/mongodb_default_profile.rb
> DEVOPS-4063: Add tpsvc-dispatcher DB

- packer/etc/yum.repos.d/centos-talend.repo
- packer/template.json.erb
Updating the yum-plugin-s3-iam version to 1.2.2.1
> Setting yum-plugin-s3-iam to the latest version

- hieradata/puppet_role/ecs.yaml
- site/profile/manifests/docker/ecs_agent.pp
Update ecs agent version to latest version from AWS
> updated ecs version

- Puppetfile.lock
> DEVOPS-2905: new activemq-security installation

- Puppetfile.lock
updated zookeeper version for new ami
> changed zookeeper version

- Puppetfile.lock
added puppet zookeeper version
> Devops 4217

- hieradata/puppet_role/kafka.yaml
- spec/acceptance/shared/kafka.rb
See: https://jira.talendforge.org/browse/DEVOPS-4436
See: https://github.com/Talend/talend-cloud-provisioner/pull/799
> DEVOPS-4436: Add provisioning topic to Kafka

- hieradata/puppet_role/kafka.yaml
related to https://github.com/Talend/platform-services-logging/pull/28/ and https://github.com/Talend/poc-kubernetes-infrastructure/pull/108/
> DEVOPS-4396: add kafka topic for system logs

- Puppetfile.lock
- hieradata/puppet_role/tic_services_internal.yaml
> DEVOPS-4572: Add provisioning karaf config to iPaaS services

- site/profile/manifests/nexus.pp
update Nexus to latest 2.x version
> nexus version update

- packer/etc/yum.repos.d/centos-talend.repo
Aligned private repos after root images creation
https://jira.talendforge.org/browse/DEVOPS-4984
> Aligned private repos

- packer/etc/yum.repos.d/centos-talend.repo
The base Url have change , i modify the path according to the new structure
> DEVOPS-5049 : Fix Base Url from Repo Format/S3 Format.

- Puppetfile.lock
- hieradata/environment/vagrant.yaml
- hieradata/puppet_role/tic_services_external.yaml
- site/profile/manifests/tic_services.pp
- spec/acceptance/tic_services_external_spec.rb
> DEVOPS-5034: Remove test data bucket

- .kitchen.yml
- Gemfile.lock
We reproduce with custom_pre_install_command what is done as pre-install in packer/template.json.erb
> workaround like packer for cloud-init / awscli conflict on urllib3 version

- hieradata/puppet_role/kafka.yaml
This PR is not sufficiant to fix the current status.
We need to automatize cluster resharding with kafka-preferred-replica-election.sh and kafka-reassign-partition.sh
> fix replica for HA, add partitions for parallelism

- hieradata/puppet_role/kafka.yaml
- spec/acceptance/shared/kafka.rb
> reconfigure kafka for our usage

- site/profile/files/usr/local/bin/kafka-topics-mgmt.sh
- site/profile/manifests/kafka.pp
- spec/acceptance/shared/kafka.rb
tested locally, and in integration
> Add management tool for Kafka admins

- site/profile/manifests/docker/registry.pp
> Fix non ASCII invisible character

- hieradata/environment/vagrant.yaml
- hieradata/puppet_role/ecs.yaml
- site/profile/manifests/docker/registry.pp
> Registries config independent from local registry

- Puppetfile.lock
Local tests passed:
```
Finished in 5.96 seconds (files took 0.29184 seconds to load)
50 examples, 0 failures
Finished verifying <role-zookeeper-centos-75> (0m6.53s).
```
> TICO-1161: Increase zookeeper version

- Puppetfile.lock
- spec/acceptance/frontend_spec.rb
DEVOPS-5537 : Add check for New app and update PUPPET TIC
> DEVOPS-5537 : Add check for New app and update PUPPET TIC

- Puppetfile.lock
> DEVOPS-5537: Upgrade Puppet Tic Version

- Puppetfile.lock
DEVOPS-5537: Change Puppet Tic Version
> DEVOPS-5537: Change Puppet Tic Version

- Puppetfile.lock
Devops-5537: ipaas redirection
> Devops-5537: ipaas redirection

- Puppetfile.lock
Pr to change Puppet Tic Version
> DEVOPS-5492 : Change Puppet Tic version

- Puppetfile
- Puppetfile.lock
- hieradata/common.yaml
- hieradata/puppet_role/kafka.yaml
- hieradata/puppet_role/zookeeper.yaml
- site/profile/manifests/kafka.pp
- site/profile/manifests/zookeeper.pp
> DEVOPS-4884 Add jmx_exporter for kafka

- hieradata/common.yaml
* Use Node Exporter v0.17.0
* Use Cadvisor v0.32.0
> feat(Prometheus): update Node Exporter & Cadvisor

- Puppetfile.lock
Bump new version to support https://jira.talendforge.org/browse/TMC-16190
> puppet tic version bump

- packer/etc/yum.repos.d/centos-talend.repo
Aligned private repos after root images creation
https://jira.talendforge.org/browse/DEVOPS-6218
> Aligned repos for new root ami

- Puppetfile.lock
> Change Puppet-tic version

- Gemfile.lock
See: https://jira.talendforge.org/browse/DEVOPS-5411
> DEVOPS-5411: Update minitar

- packer/template.json.erb
This reverts commit c4ff667d50123585b6f4d815fc465b2f2d5198dd.
> Revert "Set aws-core to version 3.46.2"

- Puppetfile.lock
> TMC-17012: Update Puppet-tic version

- packer/etc/yum.repos.d/centos-talend.repo
> DEVOPS-6841: new root ami has updated

- Puppetfile.lock
https://jira.talendforge.org/browse/DEVOPS-7139
> Bump puppet-tic

- hieradata/puppet_role/kafka.yaml
https://jira.talendforge.org/browse/TSD-354
> feat(TSD-354): remove old tsd topic

- hieradata/puppet_role/kafka.yaml
https://jira.talendforge.org/browse/DEVOPS-7500
> Kafka topic for TMC live updates

- Puppetfile.lock
Finalization of memcache remove from IPAAS
> puppet-tic version bump-up

- Puppetfile.lock
Updating nexus commit for the changes to run the service by root user
> Updating nexus commit for the changes to run the service by root user

- Gemfile.lock
- site/profile/manifests/base.pp
- spec/acceptance/shared/base.rb
> update sshd logging level to verbose

- hieradata/puppet_role/kafka.yaml
e.g. https://jira.talendforge.org/browse/TSD-482
> feat(TSD-482): add new kafka topic for TSD

- hieradata/puppet_role/frontend.yaml
Issue in logrotation from tomcat logs
Fix user and group command and review file log size
https://jira.talendforge.org/browse/TMC-20283
- [+ ] The PR commit message follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md)
- [-] Tests for the changes have been added (for bug fixes / features)
- [-] Docs have been added / updated (for bug fixes / features)
- [-] Related design / discussions / pages (not in JIRA), if any, are all linked or available in the Pull Request
> Tmc 20283 gclog rotation

- hieradata/puppet_role/frontend.yaml
e.g. https://jira.talendforge.org/browse/XXX
> Fix bad value

- hieradata/puppet_role/frontend.yaml
Fixed  logrotate roles
Delete su values
e.g. https://jira.talendforge.org/browse/XXX
> Update logrotate su values

- Puppetfile.lock
- hieradata/puppet_role/activemq.yaml
Need to update IPAAS webhook DB
Update DB schema
https://jira.talendforge.org/browse/DEVOPS-8808
> DEVOPS-8808 Update postgresql schema to use new Webhook DB

- Puppetfile.lock
- hieradata/puppet_role/activemq.yaml
Revert commit
https://github.com/Talend/talend-cloud-installer/pull/327/files
> Revert DEVOPS-8808

- Puppetfile.lock
- hieradata/puppet_role/activemq.yaml
- site/profile/manifests/postgresql/role.pp
Update IPAAS webhook DB
Add DB `extension` 
Update DB schema
https://jira.talendforge.org/browse/DEVOPS-8808
> DEVOPS-8808 Update ActiveMQ and add DB extensions

- hieradata/puppet_role/kafka.yaml
For the audit logs, we need to create a new topic in the customer logs kafka cluster
e.g. https://jira.talendforge.org/browse/DEVOPS-9122
> DEVOPS-9122: Audit logs topic

- site/profile/files/etc/systemd/system/mongod.service
This PR solves too many open files issue with the mongodb servers.
Modified service script by adding infinity value
https://jira.talendforge.org/browse/DEVOPS-9501
> DEVOPS-9501: openfile limit update

- site/profile/files/etc/systemd/system/mongod.service
Reverts Talend/talend-cloud-installer#334
> Revert "DEVOPS-9501: openfile limit update"

- site/profile/files/etc/security/limits.d/mongod.conf
- site/profile/files/etc/sysctl.d/mongod.conf
- site/profile/files/etc/systemd/system/mongod.service
- spec/acceptance/shared/mongodb.rb
This PR solves too many open files issue with the MongoDB servers.
Modified service script modifying to 256000 value
https://jira.talendforge.org/browse/DEVOPS-9501
> DEVOPS-9501: Updating the no limit value for mongod service

- packer/etc/yum.repos.d/centos-talend.repo
Adding extra repository needed for docker CE
Adding it
https://jira.talendforge.org/browse/DEVOPS-9905
> DEVOPS-9905: Adding extras repository needed for docker dependancies

- hieradata/puppet_role/activemq.yaml
Amq sec issue on EKS due to chnaghe in endpoint
Correct the path
https://jira.talendforge.org/browse/DEVOPS-11107
> Devops 11107 activemqsec

- .kitchen.yml
- Puppetfile.lock
- hieradata/puppet_role/activemq.yaml
- site/profile/manifests/activemq.pp
- spec/acceptance/shared/activemq.rb
We need network of broker capacity for Activemq for infra-parity migration
Bringing it
https://jira.talendforge.org/browse/DEVOPS-11474
> chore(DEVOPS-11474): Add ActiveMQ broker option

- hieradata/puppet_role/activemq.yaml
- spec/acceptance/shared/activemq.rb
amq version deployed is buggy
Deliver a new ActiveMQ version
https://jira.talendforge.org/browse/DEVOPS-11863
> feat(DEVOPS-11863): deploy fixed ActiveMQ version 5.15.13-3
