site/profile/manifests/base.pp

bug(missing_pip_command): fix ordering of puppet classes in profile::base
* awscli must be executed after profile::base::cloudwatch (to get puppet-python & pip)

Fix missing pip command

---

site/profile/manifests/base.pp

Fix : force the installation of pip through "tracywebtech/pip" (already used as a dependency).
Order this with the cloudwatch agent & awscli classes.

bug(missing pip command)

---

hieradata/common.yaml

feat(DEVOPS-1631): add the name of the CF main stack to CLoudwatch custom namespace

DEVOPS-1631 : use main stack name in Cloudwatch custom namespace

---

hieradata/puppet_role/tic_services_internal.yaml

We may have stacks instantiated in regions where SES is not present.

add region for ses mail

---

site/profile/manifests/mongodb.pp
spec/acceptance/shared/mongodb.rb

With strong HW, there is not enough disk space on the system for the swap.
So, for mongo, we put it in the data volume once the rights for mongo user has been modified (swap stays for root only).
Tested locally:
``` bash
(DEVOPS-3361-fix-swap-place) λ ./scripts/local_dev_tests.sh -t role-mongodb-centos-73
...
Finished in 8.69 seconds (files took 0.29349 seconds to load)
131 examples, 0 failures
...
```

fix swap location for MongoDB

---

.kitchen.yml
Puppetfile.lock
hieradata/environment/vagrant.yaml
hieradata/puppet_role/mongodb.yaml
site/profile/manifests/mongodb.pp
site/profile/manifests/mongodb/collection.pp
site/profile/manifests/mongodb/is_primary.pp
site/profile/manifests/mongodb/role.pp
site/profile/manifests/mongodb/rs_config.pp
site/profile/manifests/mongodb/user.pp
spec/acceptance/mongodb_default_profile_spec.rb
spec/acceptance/mongodb_spec.rb
spec/acceptance/mongodb_tds_profile_spec.rb
spec/acceptance/mongodb_versioned_spec.rb
spec/acceptance/shared/mongodb.rb
spec/acceptance/shared/mongodb_default_profile.rb
spec/acceptance/shared/mongodb_tds_profile.rb

Common work with @jmlrt to add profiling for MongoDB and being able to create a new replicaset with MongoDB 3.4.
Tested on talend-cloud-integration-tds-mongodb
Local tests:
``` bash
./scripts/local_dev_tests.sh -t role-mongodb-tds-profile-centos-73
...
Finished in 11.61 seconds (files took 0.31261 seconds to load)
131 examples, 0 failures
Finished verifying <role-mongodb-tds-profile-centos-73> (0m12.31s).
-----> Destroying <role-mongodb-tds-profile-centos-73>...
==> default: Forcing shutdown of VM...
==> default: Destroying VM and associated drives...
Vagrant instance <role-mongodb-tds-profile-centos-73> destroyed.
Finished destroying <role-mongodb-tds-profile-centos-73> (0m3.31s).
Finished testing <role-mongodb-tds-profile-centos-73> (7m35.24s).
-----> Kitchen is finished. (7m35.44s)
``` …

Devops 3626 mongodb profiles

---

site/profile/manifests/kafka/broker_topic.pp

I found that if a kafka topic already exists and then we want to add more than one topic level config, pnow can succeed but the output is empty when checking the topic config:
/opt/kafka/bin/kafka-configs.sh --zookeeper 10.72.4.17:2181/talend-cloud-integration-infra-kafka-apps --entity-type topics --entity-name dqDictionary --describe
So I dig out that our current code can work on config "alter" for one config but not for more.
When there are more than one options, our current command is:
--alter --add-config key=value --add-config key=value 
According to /opt/kafka/bin/kafka-configs.sh --help, it should be:
--alter  --add-config 'key=value,key=value'
/opt/kafka/bin/kafka-configs.sh --help
Option              Description                            
------              ----------- …

Fix topic config alter command for more than one options

---

hieradata/common.yaml

@mmeyer-talend 
As far as I understand, it is not necessary to adapt any tests, since the tests should find and test the new packages automatically:
In https://github.com/Talend/talend-cloud-installer/blob/ab6b7519b8b7e86a2922b6a9b8d275e4fb2263ac/spec/acceptance/shared/common/packages.rb#L1
the test creates an array and fills it with the content of _'profile::common::packages'_ , iterates over it and executes the following test for each item:
https://github.com/Talend/talend-cloud-installer/blob/ab6b7519b8b7e86a2922b6a9b8d275e4fb2263ac/spec/acceptance/shared/common/packages.rb#L3-L5
In the class 'profile::common::packages' it hashes the contents from the hiera 'common_packages'
https://github.com/Talend/talend-cloud-installer/blob/ab6b7519b8b7e86a2922b6a9b8d275e4fb2263ac/site/profile/manif …

DEVOPS-3922: Introduced two new standard packages

---

hieradata/puppet_role/kafka.yaml

The goal is to have a 1 hour retention for all the datastreams kafka topics.
The 1h period was decided with agreement from PO and security.

TFD-3179 limit streams kafka topic retention

---

.kitchen.yml

I had a blocker yesterday relative to https://github.com/test-kitchen/kitchen-vagrant/issues/347
So I made the workaround to fix VM names.
BTW, I removed the useless secondary disk for management_proxy profile

fix centos version and vagrant naming workaround

---

.kitchen.yml
site/profile/manifests/kafka/broker_topic.pp

tested locally:
```
./scripts/local_dev_tests.sh -t role-kafka-centos-74
Finished in 34.6 seconds (files took 0.62982 seconds to load)
73 examples, 0 failures
Finished verifying <role-kafka-centos-74> (0m35.64s).
-----> Destroying <role-kafka-centos-74>...
==> default: Forcing shutdown of VM...
==> default: Destroying VM and associated drives...
Vagrant instance <role-kafka-centos-74> destroyed.
Finished destroying <role-kafka-centos-74> (0m3.33s).
Finished testing <role-kafka-centos-74> (9m13.87s).
-----> Kitchen is finished. (9m14.07s)
```

change zookeeper connect string

---

Puppetfile
Puppetfile.lock

More info in the jira : https://jira.talendforge.org/browse/DEVOPS-4665

DEVOPS-4665 : upgrade puppet monitoring to reduce scraped data by cadvisor

---

hieradata/puppet_role/tic_services_external.yaml

Added the same config as for internal services

DEVOPS-4572: provisioning karaf config to iPaaS services external

---

hieradata/puppet_role/activemq.yaml
spec/acceptance/activemq_spec.rb

DEVOPS-4905: Upgrade java to 1.8.0_181 for ActiveMQ

---

hieradata/puppet_role/tic_services_internal.yaml

Idea is to use internal LB fro TIC Services external instead of special internet-faced LB for webhooks.
LTS service URL works in the same way.

DEVOPS-3766: switch to internal LB for webhooks service

---

.kitchen.yml
Puppetfile
Puppetfile.lock
hieradata/puppet_role/mongodb.yaml
site/profile/files/etc/systemd/system/mongod.service
site/profile/manifests/mongodb.pp
spec/acceptance/shared/mongodb.rb

tested locally with:
`./scripts/local_dev_tests.sh -t role-mongodb-centos-75`
`./scripts/local_dev_tests.sh -t role-mongodb-versioned-centos-75`
`./scripts/local_dev_tests.sh -t role-mongodb-tds-profile-centos-75`
All tests successfull. We need to modify extrafile before applying it in master to prepare migration.

DEVOPS-5160: mongodb upgrade

---

site/profile/manifests/kafka.pp

tested with
```
./scripts/local_dev_tests.sh -t role-kafka-centos-75
...
role::kafka
should be file
content
should exist
should exist
behaves like profile::common::cloudwatch
File "/opt/cloudwatch-agent/metrics.yaml"
content
should include "  metrics:"
content …
```

update Kafka to 1.1.1

---

site/profile/files/etc/security/limits.d/mongod.conf
site/profile/files/etc/sysctl.d/mongod.conf
site/profile/files/etc/systemd/system/mongod.service
site/profile/manifests/mongodb.pp
spec/acceptance/shared/mongodb.rb

Tested locally
```
./scripts/local_dev_tests.sh -t role-mongodb-centos-75
...
role::mongodb
should be file
content
should exist
should exist …
```

DEVOPS-5417: increase MongoDB nofile and nproc

---

site/profile/manifests/activemq.pp

tested locally:
```
λ git diff hieradata/environment/vagrant.yaml
diff --git a/hieradata/environment/vagrant.yaml b/hieradata/environment/vagrant.yaml
index 5a65325..7d430d0 100644
--- a/hieradata/environment/vagrant.yaml
+++ b/hieradata/environment/vagrant.yaml
@@ -50,6 +50,7 @@ postgresql::globals::default_connect_settings:
activemq::pg_host: "localhost"
activemq::persistence_pg_host: "localhost"
+profile::activemq::with_postgresql_optimizations: false
profile::postgresql::roles:
```
then it's failing on activemq optimizations verifications as expected
```
./scripts/local_dev_tests.sh -t role-activemq-centos-75
...
Notice: Database optimizations explicitely ignored
Notice: /Stage[main]/Profile::Activemq/Notify[Database optimizations explicitely ignored]/message: defined 'message' as …
```

db optimizations optionnals

---

hieradata/common.yaml

There is an issue in ami, some files/dirs. will be created by the newly created user if not specified in  puppet code. It will cause permission issue on file access, e.g. user/group should be kafka not jmx_exporter/cbiermann.
bash-4.2# ls -l /var/lib/kafka
total 136
rw-rr- 1 jmx_exporter cbiermann 62 1月 15 09:31 cleaner-offset-checkpoint
drwxr-xr-x 2 jmx_exporter cbiermann 141 9月 13 15:13 __consumer_offsets-0
drwxr-xr-x 2 jmx_exporter cbiermann 141 9月 13 15:13 __consumer_offsets-1
drwxr-xr-x 2 jmx_exporter cbiermann 141 9月 13 15:13 __consumer_offsets-10
drwxr-xr-x 2 jmx_exporter cbiermann 141 9月 13 15:14 __consumer_offsets-11
drwxr-xr-x 2 jmx_exporter cbiermann 141 9月 13 15:14 __consumer_offsets-12
This issue is not caused by jmx_exporter module, it happens just because the user …

DEVOPS-4884 fix user/group pb in kafka ami

---

site/profile/manifests/activemq.pp
site/profile/manifests/kafka.pp
site/profile/manifests/zookeeper.pp

jmx_exporter should be installed before kafka/zookeepr/activemq, otherwise when kafka/zookeepr/activemq service is started with agent, the jmx jar/config file may not be ready.

DEVOPS-4884 fix jmx_exporter class dependency pb

---

site/profile/manifests/kafka.pp

According to many tests I did, there is a common issue in device mount. The ownership of files under mount device is random. We already have such a fix in https://github.com/Talend/talend-cloud-installer/blob/master/site/profile/manifests/common/mount_device/fixup_ownership.pp, and it is used in mongo profile which needs to mount device also. https://github.com/Talend/talend-cloud-installer/blob/master/site/profile/manifests/mongodb.pp#L269
Here is  the ownership of files under /var/lib/kafka, sometimes it's right kafka:kafka, so it's random.
drwxr-xr-x 2 1000 1027   178 1月  17 10:37 userflow-changed-8
drwxr-xr-x 2 1000 1027   141 9月  13 17:30 websocket-to-app-0
drwxr-xr-x 2 1000 1027   178 1月  17 13:37 websocket-to-app-1
drwxr-xr-x 2 1000 1027   178 1月  17 14:07 websocket-to-app-10 …

DEVOPS-4884 Fix ownership pb in mount for kafka

---

Puppetfile

* use latest puppet-monitoring
* don't monitor Docker filesystems (leave that to Cadvisor)

fix(ECS): fix Node Exporter error logs on ECS instances

---

hieradata/puppet_role/mongodb.yaml

* MongoDB exporter uses also the 'read' permission on 'local' database

fix(MongoDB): add missing rights for MongoDB exporter user

---

.kitchen.yml
Puppetfile.lock
hieradata/puppet_role/zookeeper.yaml
spec/acceptance/shared/zookeeper.rb

tested with:
``` bash
λ ./scripts/local_dev_tests.sh -t role-zookeeper-centos-76
...
role::zookeeper
should be file
content
should exist
should exist …
```

Devops-6319: zookeeper fix

---

Puppetfile.lock
site/profile/manifests/postgresql/install.pp
spec/acceptance/shared/activemq.rb

local test:
```
role::activemq
should be file
content
should exist
should exist
configuration [/etc/awslogs/awslogs.conf]
should include "file = …
```

Update postgresql libraries for activemq and tests

---

Puppetfile.lock
hieradata/puppet_role/frontend.yaml

Adding GC logs export to follow recuring issue with gc overrhead on prod EU.

TMC-18392: Add export GC logs for frontend and Bump Puppet-tic

---

hieradata/common.yaml

tested locally:
```bash
λ ./scripts/local_dev_tests.sh -t role-activemq-centos-76
....
....
Finished in 5.32 seconds (files took 0.24911 seconds to load)
68 examples, 0 failures
Finished verifying <role-activemq-centos-76> (0m5.84s).
-----> Destroying <role-activemq-centos-76>...
==> default: Forcing shutdown of VM...
==> default: Destroying VM and associated drives...
Vagrant instance <role-activemq-centos-76> destroyed.
Finished destroying <role-activemq-centos-76> (0m2.99s).
Finished testing <role-activemq-centos-76> (20m25.69s).
```

fix rake version to latest compatible with Centos 7 ruby

---

site/profile/manifests/nginx_amq_reverseproxy.pp

The communication from Nginx to local ActiveMQ tries to use IPv6 because of localhost resolution.
We have noticed a lot of up/down on Pingdom.
Error raised on nginx logs
```
2019/11/12 23:28:37 [error] 12669#12669: *303 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 10.72.0.99, server: _, request: "POST / HTTP/1.1", upstream: "http://[::1]:8080/", host: "msg.at.cloud.talend.com"
```
Replace by 127.0.0.1 solves the issue.
Also increase the connection time to 60s, as its default value.

fix(DEVOPS-8075): set localhost as ip

---

.kitchen.yml
hieradata/puppet_role/ecs.yaml
site/profile/manifests/docker/ecs_agent.pp

https://github.com/aws/amazon-ecs-agent/releases/tag/v1.34.0
```
Finished in 17.42 seconds (files took 0.37879 seconds to load)
69 examples, 0 failures
Finished verifying <role-ecs-centos-77> (0m18.22s).
-----> Destroying <role-ecs-centos-77>...
/home/eseite/dev/Talend/talend-cloud-installer/vagrant/second_disk.rb:1: warning: already initialized constant VAGRANTFILE_API_VERSION
/home/eseite/dev/Talend/talend-cloud-installer/vagrant/2cpu-2gb.rb:1: warning: previous definition of VAGRANTFILE_API_VERSION was here
==> default: Forcing shutdown of VM...
==> default: Destroying VM and associated drives...
Vagrant instance <role-ecs-centos-77> destroyed.
Finished destroying <role-ecs-centos-77> (0m3.30s).
Finished testing <role-ecs-centos-77> (19m29.12s).
-----> Kitchen is finished. (19m29.45s) …
```

Update ecs agent to 1.34.0

---

Puppetfile
Puppetfile.lock
hieradata/common.yaml
hieradata/puppet_role/activemq.yaml
spec/acceptance/shared/activemq.rb

```
role::activemq
should be file
content
should exist
should exist
configuration [/etc/awslogs/awslogs.conf]
should include "file = …
```

DEVOPS-8513: ActiveMQ patched + new monitoring

---

hieradata/puppet_role/kafka.yaml

Jira: https://jira.talendforge.org/browse/DEVOPS-8284
- Following the #306, enlarge message size to 100MiB on Kafka topic `tmc_logs`.
(default was 1MiB)
- Set *segment.ms* to 5 minutes.
To be exhaustive, incoming message limitation is also defined on ActiveMQ config :
https://github.com/Talend/talend-cloud-installer/blob/master/hieradata/puppet_role/activemq.yaml#L12

DEVOPS-8284 enlarge topics msg size

---

site/profile/files/etc/sysctl.d/activemq_jetty.conf
site/profile/manifests/activemq.pp
spec/acceptance/shared/activemq.rb

Kernel tuning for ActiveMQ and being able to handle 3000 connections and more:
```
role::activemq
should be file
content
should exist
should exist …
```

DEVOPS-8569: Tuning Jetty for ActiveMQ

---

hieradata/common.yaml
hieradata/environment/ami.yaml
site/profile/manifests/mongodb.pp
spec/acceptance/shared/mongodb.rb

We are retiring mongodb exporter running locally on instances.
* remove the usage of the mongodb exporter Puppet class & tests.
https://jira.talendforge.org/browse/DEVOPS-6356

feat(DEVOPS-6356): remove MongoDB exporter

---

hieradata/puppet_role/ecs.yaml
site/profile/manifests/docker/datadog_docker_agent.pp

The old dd version is not usable anymore and hence updating it to the new version
Updating the dd docker version to 12.7.5327 
https://jira.talendforge.org/browse/DEVOPS-9900

fix(DEVOPS-9900): Updating datadog version for ami

---

hieradata/puppet_role/activemq.yaml

Activemqsec service is now hold on K8s on port 80 instead of 8080 on Ec2
Modify auth_url: value from 8080 to 80
https://jira.talendforge.org/browse/DEVOPS-11107

Change target port for activemqsec on k8s

---

site/profile/manifests/nexus/nginx.pp
spec/acceptance/shared/nexus.rb

the Nexus healthcheck is giving only nginx status and global nexus access status, not local one.
Having a real Nexus healthcheck implemented
https://jira.talendforge.org/browse/DEVOPS-11506

chore(DEVOPS-11506): Add a real healthcheck for Nexus

---

hieradata/environment/vagrant.yaml
hieradata/puppet_role/activemq.yaml
site/profile/manifests/activemq.pp
spec/acceptance/shared/activemq.rb

Ipaas databases are now modified by 2 paths (amq node A and new K8s provisioning)
Removing amq provisioning + update AMQ and HukariDB spooler BTW
https://jira.talendforge.org/browse/DEVOPS-11587

feat(DEVOPS-11587): Remove Shared database provisioning for Ipaas + update ActiveMQ
